<?php 
//**Used for reseting the user's password(autogenerated password)**//

require_once "../includes/functions.inc.php"; 

if (isset($_GET['email']) && isset($_GET['token'])) {             //Checking if the user used the correct method to access this file ,through the link on his email//

    require_once "../includes/db.inc.php";

    
    $email = $link->real_escape_string($_GET['email']);           //Uses $_GET variables (email and token) passed through the link//
    $token = $link->real_escape_string($_GET['token']);

    $result= $link->query=("SELECT usersId FROM users WHERE usersEmail='$email' AND token='$token' AND token<>'' AND tokenExpire > NOW() ");    //Authenticating the user and checking if his token is expired or not//

    if ($result) {                                                                                                 //If the authentication was successful//
        $newPassword = generateNewToken();                                                                         //Generates a new password//
        #$newPasswordEncrypted = password_hash($newPassword, PASSWORD_DEFAULT);                                    //Encrypts password,hashing//
        $link->query("UPDATE users SET token='', usersPassword = '$newPassword' WHERE usersEmail='$email' ");      //Updates our db with the new password//

        echo "<script>alert('Your new password is: $newPassword')</script>";                                       //Reveals the password to the user in form of an alert message// 
        echo "<script>window.close();</script>";                                                                   //on a new tab which will close when "OK" is press//
    } else
        header("location:../Login/login.php");
    
} else {
    header("location:../Login/login.php");                       //if not, redirects to the Login.php page//
}
